### ISSUE TITLE
模型找不到

### ISSUE THREAD

**Issue by renji001** [linyiLYi/voice-assistant#12]
模型放在脚本同级的models文件夹里了，为什么脚本报错找不到模型呢。。。

**Comment by renji001** [comment]
Traceback (most recent call last):
  File "/******dev/voice-assistant/main.py", line 154, in <module>
    llm = LlamaCpp(
          ^^^^^^^^^
  File "/******/VoiceAI/lib/python3.11/site-packages/langchain_core/load/serializable.py", line 97, in __init__
    super().__init__(**kwargs)
  File "/******VoiceAI/lib/python3.11/site-packages/pydantic/v1/main.py", line 341, in __init__
    raise validation_error
pydantic.v1.error_wrappers.ValidationError: 1 validation error for LlamaCpp
__root__
  Could not load Llama model from path: models/yi-chat-6b.Q8_0.gguf. Received error  (type=value_error)

**Comment by CambridgeZ** [comment]
蹲一下，我也出现了相同的问题

**Comment by AlkeneSun** [comment]
same error

**Comment by linyiLYi** [comment]
代码文件 main.py 第 21 行指定了模型文件，默认是 Yi-34B：MODEL_PATH = "models/yi-34b-chat.Q8_0.gguf"
如果你下载的是 8B 模型，或者使用了文件名和目前第 21 行不一样的模型文件，需要把 21 行这里改成你使用的模型文件名。
